openapi: 3.0.3
info:
  title: Pinokio API
  version: 1.0.0
  description: Example API spec for testing client generation

servers:
  - url: http://localhost:8000/api
    description: Local development server

paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/{id}:
    get:
      summary: Get a single user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "usr_abc123"
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          example: "john@example.com"
